### ISSUE TITLE
Top-level eligibility questions

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#262]
As a BEARS site user, in order to not get overwhelmed with the amount of eligibility questions on a life event page, I would like my experience on BEARS to be customized based on my answers to a few top-level questions. (moved from #167 )

AND 

As a BEARS content manager, in order to provide BEARS users with a reduced and tailored list of eligibility questions, I would like to be able to indicate which eligibility questions are top-level and how they customize user experience.

Pre-conditions:

- #261 is completed

Acceptance Criteria:

- The user can provide answers to the top-level eligibility questions that are displayed at the top of the criteria section on each life event page: https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/screen/48053977-bc1b-4cea-978b-49fcb2dcc29a/
- Answers to top-level questions determine visibility of the follow-up questions (greyed out / inactive)

AND

- Content manager can setup top-level edibility criteria questions for each life event (via life-event.md)
  - Top-level eligibility questions box is fully hidden if the those questions are not setup
  - Top-level question setup is unique for each life event
- Content manager can indicate which eligibility criteria are associated with top-level criteria
- If top-level criteria are Boolean type:
  - If unknown, the follow-up questions are active
  - If yes, the follow-up questions are active
  - If no, the follow-up questions are greyed-out and inactive
- If answers to the top-level questions disqualifies the user from any benefits, those benefits are treated the same way they are right now (showing eligible or not eligible indicators)

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [ ] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [ ] Usability testing
- [x] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by fpigeonjr** [comment]
## Proposal
1. Add top-level eligibility criteria questions to the `criteria.csv`
`| tl_applicant_served_in_military | Did you serve in the military?| radio | yes; no |`
2. Then add to the `life-event.md`
```yaml
// military-service.md

// this would be the top-level
eligibilityCriteria:
- label: "Start here"
  criteriaGroupKey: top-level
  // keys match criteria.csv in step 1
  // allow for more than one
  criteriaKeys:
    - tl_applicant_served_in_military
    acceptableValues: ["yes"]
// child criteria
- label: "About you (the person applying for benefits)"
    description: ""
    // associate top-level criteria
    topLevelCriteriaKey:
    - tl_applicant_served_in_military
    // select keys to hide
    hideCriteriaKeys:
    - applicant_served_in_active_military
    criteriaGroupKey: applicant
    criteriaKeys:
      - applicant_served_in_active_military
      - applicant_disability
      - applicant_marital_status
```
3. Manage state of the top-level question as it relates to the child criteria
	1. Default is active, only disable if top-level criteria is not-met.
	2. If top-level is answered according to the `acceptableValues`, then activate `is-disabled` prop for each of the components in the `CriteriaChild` component i.e. `<CheckBox/>, <DropDown>`, etc. This will apply disabled styles for the component so users will not be able to interact with it.
```javascript
// CriteriaChild.vue
<CheckBox
  :criteria-key="criteriaKey"
  :label="getCriterionLabel()"
  :response="response"
  :is-disabled="isCriteriaDisabled"
  location="left-rail" />
```


## Questions
- I am assuming we always want to show all the benefit cards in the right-rail?
- This would only impact the left-rail?

**Comment by fpigeonjr** [comment]
thanks @r-bartlett-gsa for helping me think thru this today. Updated the proposal above based on our conversation.

**Comment by fpigeonjr** [comment]
## Proposal 2
1. Add top-level eligibility criteria questions to the `criteria.csv`
`| applicant_served_in_military | Did you serve in the military?| radio | yes; no |`
2. Then add to the `life-event.md`
```yaml
// military-service.md

topLevelFilter:
- label: "Start here"
  criteriaKey:
  - applicant_served_in_military
  childGroupKey: applicant
  disableWhen: ["no"]
  
- label: "Start here"
  criteriaKey:
  - deceased_served_in_military
  childGroupKey: military
  disableWhen: ["died on active duty","had retired from the service", "was discharged under conditions other than dishonorable" ]
 
eligibilityCriteria:
- label: "About you (the person applying for benefits)"
  description: ""
  criteriaGroupKey: applicant
  criteriaKeys:
    - applicant_served_in_active_military
    - applicant_disability
    - applicant_marital_status
    
 - label: "Did you lose a loved one who served in military?"
    description: ""
    criteriaGroupKey: military
    criteriaKeys:
      - applicant_relationship
      - deceased_served_in_active_military
      - deceased_buried_in_unmarked_grave
      - deceased_headstone_is_privately_purchased
      - deceased_buried_in_private_cemetery
```

**Comment by fpigeonjr** [comment]
thanks @jschoenemann-cms for helping with this second proposal.

**Comment by fpigeonjr** [comment]
Made a minor modification this morning on the topLevelFilter_criteriaKey to singular since we will have one top-level filter per child group.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr / @jschoenemann-cms A few questions/comments in regards to Proposal 2:

- If there are multiple topLevel filters, will only the first label (Start here) display on the front-end? What will be displayed if a label is provided for each topLevel filter?
- If topLevel filter is not associated with any childGroup nor it disables any child criteria, should the childGroupKey and disableWhen be left blank? (topLevel filters should still interact with benefits the way any other criteria currently does)

**Comment by jschoenemann-cms** [comment]
> * If topLevel filter is not associated with any childGroup nor it disables any child criteria, should the childGroupKey and disableWhen be left blank? (topLevel filters should still interact with benefits the way any other criteria currently does)

This could go either way.  We could:
1. Say top level questions require "child criteria" reason being that if it does't disable anything its not really a top level question.  In this condition maybe we should have some type of an error highlighting an issue with the content configuration.
or
2. Allow this behavior.  The top level filter doesn't disable any questions, but does impact the benefit card sorting etc.  It becomes a style choice of the content manager choosing to place the question in a top level area vs a standard question. 

We can make this work either way.  What do you think?

**Comment by jschoenemann-cms** [comment]
> * If there are multiple topLevel filters, will only the first label (Start here) display on the front-end? What will be displayed if a label is provided for each topLevel filter?

Each label will be a header for the top level question.  So each question will get its own label.  It can be left blank and no header will appear. 

We currently don't have a "group" for the top level questions.  This assumes top level questions are special and grouped together by nature.   Is that the correct desired behavior?

**Comment by r-bartlett-gsa** [comment]
@jschoenemann-cms 

> - If topLevel filter is not associated with any childGroup nor it disables any child criteria, should the childGroupKey and disableWhen be left blank? (topLevel filters should still interact with benefits the way any other criteria currently does)

Please allow this behavior - ability to NOT assign child group to top level question.

---

> - If there are multiple topLevel filters, will only the first label (Start here) display on the front-end? What will be displayed if a label is provided for each topLevel filter?

Everything you said sounds good - ability to leave the top level header blank and top level questions being a group on its own, and no grouping within.

**Comment by jschoenemann-cms** [comment]
new issue created to refactor so criteria key is not an array #360

**Comment by fpigeonjr** [comment]
This is where we landed on the `life-event.md` until we work on #360. I'll make sure and add this to the `content/readme`.

```yaml
// military-service.md
topLevelFilter:
  - label: "Start here"
    criteriaKey:
      - applicant_served_in_active_military
    disableGroupKey: applicant
    disableGroupWhen: ["not applicable"]

  - label: ""
    criteriaKey:
      - deceased_served_in_active_military
    disableGroupKey: military
    disableGroupWhen: ["not applicable"]
```
