### ISSUE TITLE
Update pa11y action

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#568]
The pa11y action is failing for some builds, not on running the tests, but on the commenting action after the tests have concluded, even if they were successful.

There's a new version of the thollander/comment-pull-request action (v2 is latest; [we're using v1](https://github.com/GSA/usagov-benefits-eligibility/blob/main/.github/workflows/pa11y.yml#L42-L48))

https://github.com/marketplace/actions/comment-pull-request

Also, there is a GitHub Action available to automate what we've hard-coded:

* Action: https://github.com/marketplace/actions/pa11y-actions
* Source: https://github.com/booleans-oss/pa11y-actions

```yaml
steps:
- uses: actions/checkout@v3
- uses: browser-actions/setup-chrome@latest
- uses: booleans-oss/pa11y-actions@v1
  with:
    start: start
    port: '3000'
```
