### ISSUE TITLE
include dependabot for github actions

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#573]
in .github/dependabot.yml, add:

```yaml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

This will help us maintain GitHub Actions that get behind and/or have security or stability concerns.

reference:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
