### ISSUE TITLE
support nvmrc in GitHub Action

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#574]
```yaml
- name: Read .nvmrc
  run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
  id: nvm

- name: Use Node.js (.nvmrc)
  uses: actions/setup-node@v3
  with:
    node-version: "${{ steps.nvm.outputs.NVMRC }}"
```
