### ISSUE TITLE
Build content and taxonomy data architecture document

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#704]
# User Story
As a developer, I want to start to define the content and taxonomy architecture for the V2 version of BEARS.

https://docs.google.com/spreadsheets/d/1jo6k_z8yZtQryeKfl67W8jsGDtkFQDX1_bp4_L00lGQ/edit#gid=0

## Single Benefit fields example Mapping (i.e. a single accordion item)
Example file https://raw.githubusercontent.com/GSA/usagov-benefits-eligibility/main/content/benefits/dod-survivor-benefit-plan.md
`dod-survivor-benefit-plan`

```yaml
## title - text field on the node 
title: ""

## headline -Noting that in the BEARS data, the data for headline is identical to title so we need to confirm that.
headline: ""

## Tags - entity reference to tags vocabulary, multiple value (array) allowed. Noting that it is unclear if tags are actually being used. 
tags: []

## life events - entity reference to life events vocabulary, multiple value (array) allowed
lifeEvents: []

source:
## source name - text field on the node 
  name: ""
## source link - link field on the node
  link: ""
## Is English - Boolean on the node
  isEnglish: ""

## summary - textarea (long text) on the node
summary: ""

## Paragraph type or custom entity called "Eligibility"
eligibility:
## Paragraph type or custom entity called "Eligibility item" (nested within Eligibility)
  - criteriaKey: ""
    label: ""
    acceptableValues: [""]
  - criteriaKey: ""
    acceptableValues: [""]
  - criteriaKey: ""
    acceptableValues: [""]
  - criteriaKey: ""
    acceptableValues: [""]
```

**Comment by danny-englander** [comment]
@gchi25 Assigning to you, use the example above to help you create mapping and templates for all other data in BEARS to map from V1 to V2. You will need to complete 

```yaml
eligibility:
  - criteriaKey: ""
    label: ""
    acceptableValues: [""]
```
etc...
